/** @file sortXXL_cmd.h
 *  @brief The header file for the command line option parser
 *  generated by GNU Gengetopt version 2.22.5
 *  http://www.gnu.org/software/gengetopt.
 *  DO NOT modify this file, since it can be overwritten
 *  @author GNU Gengetopt by Lorenzo Bettini */

#ifndef SORTXXL_CMD_H
#define SORTXXL_CMD_H

/* If we use autoconf.  */
#ifdef HAVE_CONFIG_H
#include "config.h"
#endif

#include <stdio.h> /* for FILE */

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#ifndef CMDLINE_PARSER_PACKAGE
/** @brief the program name (used for printing errors) */
#define CMDLINE_PARSER_PACKAGE "sortXXL"
#endif

#ifndef CMDLINE_PARSER_PACKAGE_NAME
/** @brief the complete program name (used for help and version) */
#define CMDLINE_PARSER_PACKAGE_NAME "sortXXL"
#endif

#ifndef CMDLINE_PARSER_VERSION
/** @brief the program version */
#define CMDLINE_PARSER_VERSION "1.0"
#endif

/** @brief Where the command line options are stored */
struct gengetopt_args_info
{
  const char *help_help; /**< @brief Print help and exit help description.  */
  const char *version_help; /**< @brief Print version and exit help description.  */
  char * input_arg;	/**< @brief Text file containing the numbers to sort..  */
  char * input_orig;	/**< @brief Text file containing the numbers to sort. original value given at command line.  */
  const char *input_help; /**< @brief Text file containing the numbers to sort. help description.  */
  int random_arg;	/**< @brief Number of numbers to be generated..  */
  char * random_orig;	/**< @brief Number of numbers to be generated. original value given at command line.  */
  const char *random_help; /**< @brief Number of numbers to be generated. help description.  */
  const char *about_help; /**< @brief Application credits. help description.  */
  char * output_arg;	/**< @brief Output text file with the sorted numbers..  */
  char * output_orig;	/**< @brief Output text file with the sorted numbers. original value given at command line.  */
  const char *output_help; /**< @brief Output text file with the sorted numbers. help description.  */
  int benchmark_arg;	/**< @brief Benchmark mode. Number of times that sortXXL that will execute, presenting the execution time in the end. (default='1').  */
  char * benchmark_orig;	/**< @brief Benchmark mode. Number of times that sortXXL that will execute, presenting the execution time in the end. original value given at command line.  */
  const char *benchmark_help; /**< @brief Benchmark mode. Number of times that sortXXL that will execute, presenting the execution time in the end. help description.  */
  int min_arg;	/**< @brief Minimum value to be sorted..  */
  char * min_orig;	/**< @brief Minimum value to be sorted. original value given at command line.  */
  const char *min_help; /**< @brief Minimum value to be sorted. help description.  */
  int max_arg;	/**< @brief Maximum value to be sorted..  */
  char * max_orig;	/**< @brief Maximum value to be sorted. original value given at command line.  */
  const char *max_help; /**< @brief Maximum value to be sorted. help description.  */
  int demo_arg;	/**< @brief Demo mode with the port specification to listen for connections from HTTP clients (default='7681').  */
  char * demo_orig;	/**< @brief Demo mode with the port specification to listen for connections from HTTP clients original value given at command line.  */
  const char *demo_help; /**< @brief Demo mode with the port specification to listen for connections from HTTP clients help description.  */
  int gpu_flag;	/**< @brief Show graphic card's information. (default=off).  */
  const char *gpu_help; /**< @brief Show graphic card's information. help description.  */
  
  unsigned int help_given ;	/**< @brief Whether help was given.  */
  unsigned int version_given ;	/**< @brief Whether version was given.  */
  unsigned int input_given ;	/**< @brief Whether input was given.  */
  unsigned int random_given ;	/**< @brief Whether random was given.  */
  unsigned int about_given ;	/**< @brief Whether about was given.  */
  unsigned int output_given ;	/**< @brief Whether output was given.  */
  unsigned int benchmark_given ;	/**< @brief Whether benchmark was given.  */
  unsigned int min_given ;	/**< @brief Whether min was given.  */
  unsigned int max_given ;	/**< @brief Whether max was given.  */
  unsigned int demo_given ;	/**< @brief Whether demo was given.  */
  unsigned int gpu_given ;	/**< @brief Whether gpu was given.  */

  int data_source_group_counter; /**< @brief Counter for group data_source */
  int sortXXL_options_mode_counter; /**< @brief Counter for mode sortXXL_options */
} ;

/** @brief The additional parameters to pass to parser functions */
struct cmdline_parser_params
{
  int override; /**< @brief whether to override possibly already present options (default 0) */
  int initialize; /**< @brief whether to initialize the option structure gengetopt_args_info (default 1) */
  int check_required; /**< @brief whether to check that all required options were provided (default 1) */
  int check_ambiguity; /**< @brief whether to check for options already specified in the option structure gengetopt_args_info (default 0) */
  int print_errors; /**< @brief whether getopt_long should print an error message for a bad option (default 1) */
} ;

/** @brief the purpose string of the program */
extern const char *gengetopt_args_info_purpose;
/** @brief the usage string of the program */
extern const char *gengetopt_args_info_usage;
/** @brief all the lines making the help output */
extern const char *gengetopt_args_info_help[];

/**
 * The command line parser
 * @param argc the number of command line options
 * @param argv the command line options
 * @param args_info the structure where option information will be stored
 * @return 0 if everything went fine, NON 0 if an error took place
 */
int cmdline_parser (int argc, char **argv,
  struct gengetopt_args_info *args_info);

/**
 * The command line parser (version with additional parameters - deprecated)
 * @param argc the number of command line options
 * @param argv the command line options
 * @param args_info the structure where option information will be stored
 * @param override whether to override possibly already present options
 * @param initialize whether to initialize the option structure my_args_info
 * @param check_required whether to check that all required options were provided
 * @return 0 if everything went fine, NON 0 if an error took place
 * @deprecated use cmdline_parser_ext() instead
 */
int cmdline_parser2 (int argc, char **argv,
  struct gengetopt_args_info *args_info,
  int override, int initialize, int check_required);

/**
 * The command line parser (version with additional parameters)
 * @param argc the number of command line options
 * @param argv the command line options
 * @param args_info the structure where option information will be stored
 * @param params additional parameters for the parser
 * @return 0 if everything went fine, NON 0 if an error took place
 */
int cmdline_parser_ext (int argc, char **argv,
  struct gengetopt_args_info *args_info,
  struct cmdline_parser_params *params);

/**
 * Save the contents of the option struct into an already open FILE stream.
 * @param outfile the stream where to dump options
 * @param args_info the option struct to dump
 * @return 0 if everything went fine, NON 0 if an error took place
 */
int cmdline_parser_dump(FILE *outfile,
  struct gengetopt_args_info *args_info);

/**
 * Save the contents of the option struct into a (text) file.
 * This file can be read by the config file parser (if generated by gengetopt)
 * @param filename the file where to save
 * @param args_info the option struct to save
 * @return 0 if everything went fine, NON 0 if an error took place
 */
int cmdline_parser_file_save(const char *filename,
  struct gengetopt_args_info *args_info);

/**
 * Print the help
 */
void cmdline_parser_print_help(void);
/**
 * Print the version
 */
void cmdline_parser_print_version(void);

/**
 * Initializes all the fields a cmdline_parser_params structure 
 * to their default values
 * @param params the structure to initialize
 */
void cmdline_parser_params_init(struct cmdline_parser_params *params);

/**
 * Allocates dynamically a cmdline_parser_params structure and initializes
 * all its fields to their default values
 * @return the created and initialized cmdline_parser_params structure
 */
struct cmdline_parser_params *cmdline_parser_params_create(void);

/**
 * Initializes the passed gengetopt_args_info structure's fields
 * (also set default values for options that have a default)
 * @param args_info the structure to initialize
 */
void cmdline_parser_init (struct gengetopt_args_info *args_info);
/**
 * Deallocates the string fields of the gengetopt_args_info structure
 * (but does not deallocate the structure itself)
 * @param args_info the structure to deallocate
 */
void cmdline_parser_free (struct gengetopt_args_info *args_info);

/**
 * Checks that all the required options were specified
 * @param args_info the structure to check
 * @param prog_name the name of the program that will be used to print
 *   possible errors
 * @return
 */
int cmdline_parser_required (struct gengetopt_args_info *args_info,
  const char *prog_name);


#ifdef __cplusplus
}
#endif /* __cplusplus */
#endif /* SORTXXL_CMD_H */
