/*
  File autogenerated by gengetopt version 2.22.5
  generated with the following command:
  gengetopt --output-dir=./src/3rd/ --file-name=sortXXL_cmd 

  The developers of gengetopt consider the fixed text that goes in all
  gengetopt output files to be in the public domain:
  we make no copyright claims on it.
*/

/* If we use autoconf.  */
#ifdef HAVE_CONFIG_H
#include "config.h"
#endif

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#ifndef FIX_UNUSED
#define FIX_UNUSED(X) (void) (X) /* avoid warnings for unused params */
#endif

#include <getopt.h>

#include "sortXXL_cmd.h"

const char *gengetopt_args_info_purpose = "Ordering numbers using CUDA optimized algorithms";

const char *gengetopt_args_info_usage = "Usage: For educational proposes only.";

const char *gengetopt_args_info_description = "Program for CAD (Computação de Alto Desempenho) @ MEI-CM 2012/2013";

const char *gengetopt_args_info_help[] = {
  "  -h, --help                Print help and exit",
  "  -V, --version             Print version and exit",
  "\n Group: data source\n  the data source to use",
  "  -i, --input=inputFile     Text file containing the numbers to sort.",
  "  -r, --random=numNumbers   Number of numbers to be generated.",
  "      --about               Application credits.",
  "\n Mode: sortXXL options\n  grouping sortXXL options",
  "  -o, --output=outputFile   Output text file with the sorted numbers.",
  "  -b, --benchmark=numTimes  Benchmark mode. Number of times that sortXXL that \n                              will execute, presenting the execution time in \n                              the end.  (default=`1')",
  "  -m, --min=minNumber       Minimum value to be sorted.",
  "  -M, --max=maxNumber       Maximum value to be sorted.",
  "  -d, --demo[=portNumber]   Demo mode with the port specification to listen for \n                              connections from HTTP clients  (default=`7681')",
  "  -g, --gpu                 Show graphic card's information.  (default=off)",
    0
};

typedef enum {ARG_NO
  , ARG_FLAG
  , ARG_STRING
  , ARG_INT
} cmdline_parser_arg_type;

static
void clear_given (struct gengetopt_args_info *args_info);
static
void clear_args (struct gengetopt_args_info *args_info);

static int
cmdline_parser_internal (int argc, char **argv, struct gengetopt_args_info *args_info,
                        struct cmdline_parser_params *params, const char *additional_error);

static int
cmdline_parser_required2 (struct gengetopt_args_info *args_info, const char *prog_name, const char *additional_error);

static char *
gengetopt_strdup (const char *s);

static
void clear_given (struct gengetopt_args_info *args_info)
{
  args_info->help_given = 0 ;
  args_info->version_given = 0 ;
  args_info->input_given = 0 ;
  args_info->random_given = 0 ;
  args_info->about_given = 0 ;
  args_info->output_given = 0 ;
  args_info->benchmark_given = 0 ;
  args_info->min_given = 0 ;
  args_info->max_given = 0 ;
  args_info->demo_given = 0 ;
  args_info->gpu_given = 0 ;
  args_info->data_source_group_counter = 0 ;
  args_info->sortXXL_options_mode_counter = 0 ;
}

static
void clear_args (struct gengetopt_args_info *args_info)
{
  FIX_UNUSED (args_info);
  args_info->input_arg = NULL;
  args_info->input_orig = NULL;
  args_info->random_orig = NULL;
  args_info->output_arg = NULL;
  args_info->output_orig = NULL;
  args_info->benchmark_arg = 1;
  args_info->benchmark_orig = NULL;
  args_info->min_orig = NULL;
  args_info->max_orig = NULL;
  args_info->demo_arg = 7681;
  args_info->demo_orig = NULL;
  args_info->gpu_flag = 0;
  
}

static
void init_args_info(struct gengetopt_args_info *args_info)
{


  args_info->help_help = gengetopt_args_info_help[0] ;
  args_info->version_help = gengetopt_args_info_help[1] ;
  args_info->input_help = gengetopt_args_info_help[3] ;
  args_info->random_help = gengetopt_args_info_help[4] ;
  args_info->about_help = gengetopt_args_info_help[5] ;
  args_info->output_help = gengetopt_args_info_help[7] ;
  args_info->benchmark_help = gengetopt_args_info_help[8] ;
  args_info->min_help = gengetopt_args_info_help[9] ;
  args_info->max_help = gengetopt_args_info_help[10] ;
  args_info->demo_help = gengetopt_args_info_help[11] ;
  args_info->gpu_help = gengetopt_args_info_help[12] ;
  
}

void
cmdline_parser_print_version (void)
{
  printf ("%s %s\n",
     (strlen(CMDLINE_PARSER_PACKAGE_NAME) ? CMDLINE_PARSER_PACKAGE_NAME : CMDLINE_PARSER_PACKAGE),
     CMDLINE_PARSER_VERSION);
}

static void print_help_common(void) {
  cmdline_parser_print_version ();

  if (strlen(gengetopt_args_info_purpose) > 0)
    printf("\n%s\n", gengetopt_args_info_purpose);

  if (strlen(gengetopt_args_info_usage) > 0)
    printf("\n%s\n", gengetopt_args_info_usage);

  printf("\n");

  if (strlen(gengetopt_args_info_description) > 0)
    printf("%s\n\n", gengetopt_args_info_description);
}

void
cmdline_parser_print_help (void)
{
  int i = 0;
  print_help_common();
  while (gengetopt_args_info_help[i])
    printf("%s\n", gengetopt_args_info_help[i++]);
}

void
cmdline_parser_init (struct gengetopt_args_info *args_info)
{
  clear_given (args_info);
  clear_args (args_info);
  init_args_info (args_info);
}

void
cmdline_parser_params_init(struct cmdline_parser_params *params)
{
  if (params)
    { 
      params->override = 0;
      params->initialize = 1;
      params->check_required = 1;
      params->check_ambiguity = 0;
      params->print_errors = 1;
    }
}

struct cmdline_parser_params *
cmdline_parser_params_create(void)
{
  struct cmdline_parser_params *params = 
    (struct cmdline_parser_params *)malloc(sizeof(struct cmdline_parser_params));
  cmdline_parser_params_init(params);  
  return params;
}

static void
free_string_field (char **s)
{
  if (*s)
    {
      free (*s);
      *s = 0;
    }
}


static void
cmdline_parser_release (struct gengetopt_args_info *args_info)
{

  free_string_field (&(args_info->input_arg));
  free_string_field (&(args_info->input_orig));
  free_string_field (&(args_info->random_orig));
  free_string_field (&(args_info->output_arg));
  free_string_field (&(args_info->output_orig));
  free_string_field (&(args_info->benchmark_orig));
  free_string_field (&(args_info->min_orig));
  free_string_field (&(args_info->max_orig));
  free_string_field (&(args_info->demo_orig));
  
  

  clear_given (args_info);
}


static void
write_into_file(FILE *outfile, const char *opt, const char *arg, const char *values[])
{
  FIX_UNUSED (values);
  if (arg) {
    fprintf(outfile, "%s=\"%s\"\n", opt, arg);
  } else {
    fprintf(outfile, "%s\n", opt);
  }
}


int
cmdline_parser_dump(FILE *outfile, struct gengetopt_args_info *args_info)
{
  int i = 0;

  if (!outfile)
    {
      fprintf (stderr, "%s: cannot dump options to stream\n", CMDLINE_PARSER_PACKAGE);
      return EXIT_FAILURE;
    }

  if (args_info->help_given)
    write_into_file(outfile, "help", 0, 0 );
  if (args_info->version_given)
    write_into_file(outfile, "version", 0, 0 );
  if (args_info->input_given)
    write_into_file(outfile, "input", args_info->input_orig, 0);
  if (args_info->random_given)
    write_into_file(outfile, "random", args_info->random_orig, 0);
  if (args_info->about_given)
    write_into_file(outfile, "about", 0, 0 );
  if (args_info->output_given)
    write_into_file(outfile, "output", args_info->output_orig, 0);
  if (args_info->benchmark_given)
    write_into_file(outfile, "benchmark", args_info->benchmark_orig, 0);
  if (args_info->min_given)
    write_into_file(outfile, "min", args_info->min_orig, 0);
  if (args_info->max_given)
    write_into_file(outfile, "max", args_info->max_orig, 0);
  if (args_info->demo_given)
    write_into_file(outfile, "demo", args_info->demo_orig, 0);
  if (args_info->gpu_given)
    write_into_file(outfile, "gpu", 0, 0 );
  

  i = EXIT_SUCCESS;
  return i;
}

int
cmdline_parser_file_save(const char *filename, struct gengetopt_args_info *args_info)
{
  FILE *outfile;
  int i = 0;

  outfile = fopen(filename, "w");

  if (!outfile)
    {
      fprintf (stderr, "%s: cannot open file for writing: %s\n", CMDLINE_PARSER_PACKAGE, filename);
      return EXIT_FAILURE;
    }

  i = cmdline_parser_dump(outfile, args_info);
  fclose (outfile);

  return i;
}

void
cmdline_parser_free (struct gengetopt_args_info *args_info)
{
  cmdline_parser_release (args_info);
}

/** @brief replacement of strdup, which is not standard */
char *
gengetopt_strdup (const char *s)
{
  char *result = 0;
  if (!s)
    return result;

  result = (char*)malloc(strlen(s) + 1);
  if (result == (char*)0)
    return (char*)0;
  strcpy(result, s);
  return result;
}

static void
reset_group_data_source(struct gengetopt_args_info *args_info)
{
  if (! args_info->data_source_group_counter)
    return;
  
  args_info->input_given = 0 ;
  free_string_field (&(args_info->input_arg));
  free_string_field (&(args_info->input_orig));
  args_info->random_given = 0 ;
  free_string_field (&(args_info->random_orig));
  args_info->about_given = 0 ;

  args_info->data_source_group_counter = 0;
}

int
cmdline_parser (int argc, char **argv, struct gengetopt_args_info *args_info)
{
  return cmdline_parser2 (argc, argv, args_info, 0, 1, 1);
}

int
cmdline_parser_ext (int argc, char **argv, struct gengetopt_args_info *args_info,
                   struct cmdline_parser_params *params)
{
  int result;
  result = cmdline_parser_internal (argc, argv, args_info, params, 0);

  if (result == EXIT_FAILURE)
    {
      cmdline_parser_free (args_info);
      exit (EXIT_FAILURE);
    }
  
  return result;
}

int
cmdline_parser2 (int argc, char **argv, struct gengetopt_args_info *args_info, int override, int initialize, int check_required)
{
  int result;
  struct cmdline_parser_params params;
  
  params.override = override;
  params.initialize = initialize;
  params.check_required = check_required;
  params.check_ambiguity = 0;
  params.print_errors = 1;

  result = cmdline_parser_internal (argc, argv, args_info, &params, 0);

  if (result == EXIT_FAILURE)
    {
      cmdline_parser_free (args_info);
      exit (EXIT_FAILURE);
    }
  
  return result;
}

int
cmdline_parser_required (struct gengetopt_args_info *args_info, const char *prog_name)
{
  int result = EXIT_SUCCESS;

  if (cmdline_parser_required2(args_info, prog_name, 0) > 0)
    result = EXIT_FAILURE;

  if (result == EXIT_FAILURE)
    {
      cmdline_parser_free (args_info);
      exit (EXIT_FAILURE);
    }
  
  return result;
}

int
cmdline_parser_required2 (struct gengetopt_args_info *args_info, const char *prog_name, const char *additional_error)
{
  int error = 0;
  FIX_UNUSED (additional_error);

  /* checks for required options */
  if (args_info->data_source_group_counter == 0)
    {
      fprintf (stderr, "%s: %d options of group data source were given. One is required%s.\n", prog_name, args_info->data_source_group_counter, (additional_error ? additional_error : ""));
      error = 1;
    }
  

  /* checks for dependences among options */

  return error;
}


static char *package_name = 0;

/**
 * @brief updates an option
 * @param field the generic pointer to the field to update
 * @param orig_field the pointer to the orig field
 * @param field_given the pointer to the number of occurrence of this option
 * @param prev_given the pointer to the number of occurrence already seen
 * @param value the argument for this option (if null no arg was specified)
 * @param possible_values the possible values for this option (if specified)
 * @param default_value the default value (in case the option only accepts fixed values)
 * @param arg_type the type of this option
 * @param check_ambiguity @see cmdline_parser_params.check_ambiguity
 * @param override @see cmdline_parser_params.override
 * @param no_free whether to free a possible previous value
 * @param multiple_option whether this is a multiple option
 * @param long_opt the corresponding long option
 * @param short_opt the corresponding short option (or '-' if none)
 * @param additional_error possible further error specification
 */
static
int update_arg(void *field, char **orig_field,
               unsigned int *field_given, unsigned int *prev_given, 
               char *value, const char *possible_values[],
               const char *default_value,
               cmdline_parser_arg_type arg_type,
               int check_ambiguity, int override,
               int no_free, int multiple_option,
               const char *long_opt, char short_opt,
               const char *additional_error)
{
  char *stop_char = 0;
  const char *val = value;
  int found;
  char **string_field;
  FIX_UNUSED (field);

  stop_char = 0;
  found = 0;

  if (!multiple_option && prev_given && (*prev_given || (check_ambiguity && *field_given)))
    {
      if (short_opt != '-')
        fprintf (stderr, "%s: `--%s' (`-%c') option given more than once%s\n", 
               package_name, long_opt, short_opt,
               (additional_error ? additional_error : ""));
      else
        fprintf (stderr, "%s: `--%s' option given more than once%s\n", 
               package_name, long_opt,
               (additional_error ? additional_error : ""));
      return 1; /* failure */
    }

  FIX_UNUSED (default_value);
    
  if (field_given && *field_given && ! override)
    return 0;
  if (prev_given)
    (*prev_given)++;
  if (field_given)
    (*field_given)++;
  if (possible_values)
    val = possible_values[found];

  switch(arg_type) {
  case ARG_FLAG:
    *((int *)field) = !*((int *)field);
    break;
  case ARG_INT:
    if (val) *((int *)field) = strtol (val, &stop_char, 0);
    break;
  case ARG_STRING:
    if (val) {
      string_field = (char **)field;
      if (!no_free && *string_field)
        free (*string_field); /* free previous string */
      *string_field = gengetopt_strdup (val);
    }
    break;
  default:
    break;
  };

  /* check numeric conversion */
  switch(arg_type) {
  case ARG_INT:
    if (val && !(stop_char && *stop_char == '\0')) {
      fprintf(stderr, "%s: invalid numeric value: %s\n", package_name, val);
      return 1; /* failure */
    }
    break;
  default:
    ;
  };

  /* store the original value */
  switch(arg_type) {
  case ARG_NO:
  case ARG_FLAG:
    break;
  default:
    if (value && orig_field) {
      if (no_free) {
        *orig_field = value;
      } else {
        if (*orig_field)
          free (*orig_field); /* free previous string */
        *orig_field = gengetopt_strdup (value);
      }
    }
  };

  return 0; /* OK */
}


static int check_modes(
  int given1[], const char *options1[],
                       int given2[], const char *options2[])
{
  int i = 0, j = 0, errors = 0;
  
  while (given1[i] >= 0) {
    if (given1[i]) {
      while (given2[j] >= 0) {
        if (given2[j]) {
          ++errors;
          fprintf(stderr, "%s: option %s conflicts with option %s\n",
                  package_name, options1[i], options2[j]);
        }
        ++j;
      }
    }
    ++i;
  }
  
  return errors;
}

int
cmdline_parser_internal (
  int argc, char **argv, struct gengetopt_args_info *args_info,
                        struct cmdline_parser_params *params, const char *additional_error)
{
  int c;	/* Character of the parsed option.  */

  int error = 0;
  struct gengetopt_args_info local_args_info;
  
  int override;
  int initialize;
  int check_required;
  int check_ambiguity;
  
  package_name = argv[0];
  
  override = params->override;
  initialize = params->initialize;
  check_required = params->check_required;
  check_ambiguity = params->check_ambiguity;

  if (initialize)
    cmdline_parser_init (args_info);

  cmdline_parser_init (&local_args_info);

  optarg = 0;
  optind = 0;
  opterr = params->print_errors;
  optopt = '?';

  while (1)
    {
      int option_index = 0;

      static struct option long_options[] = {
        { "help",	0, NULL, 'h' },
        { "version",	0, NULL, 'V' },
        { "input",	1, NULL, 'i' },
        { "random",	1, NULL, 'r' },
        { "about",	0, NULL, 0 },
        { "output",	1, NULL, 'o' },
        { "benchmark",	1, NULL, 'b' },
        { "min",	1, NULL, 'm' },
        { "max",	1, NULL, 'M' },
        { "demo",	2, NULL, 'd' },
        { "gpu",	0, NULL, 'g' },
        { 0,  0, 0, 0 }
      };

      c = getopt_long (argc, argv, "hVi:r:o:b:m:M:d::g", long_options, &option_index);

      if (c == -1) break;	/* Exit from `while (1)' loop.  */

      switch (c)
        {
        case 'h':	/* Print help and exit.  */
          cmdline_parser_print_help ();
          cmdline_parser_free (&local_args_info);
          exit (EXIT_SUCCESS);

        case 'V':	/* Print version and exit.  */
          cmdline_parser_print_version ();
          cmdline_parser_free (&local_args_info);
          exit (EXIT_SUCCESS);

        case 'i':	/* Text file containing the numbers to sort..  */
        
          if (args_info->data_source_group_counter && override)
            reset_group_data_source (args_info);
          args_info->data_source_group_counter += 1;
        
          if (update_arg( (void *)&(args_info->input_arg), 
               &(args_info->input_orig), &(args_info->input_given),
              &(local_args_info.input_given), optarg, 0, 0, ARG_STRING,
              check_ambiguity, override, 0, 0,
              "input", 'i',
              additional_error))
            goto failure;
        
          break;
        case 'r':	/* Number of numbers to be generated..  */
        
          if (args_info->data_source_group_counter && override)
            reset_group_data_source (args_info);
          args_info->data_source_group_counter += 1;
        
          if (update_arg( (void *)&(args_info->random_arg), 
               &(args_info->random_orig), &(args_info->random_given),
              &(local_args_info.random_given), optarg, 0, 0, ARG_INT,
              check_ambiguity, override, 0, 0,
              "random", 'r',
              additional_error))
            goto failure;
        
          break;
        case 'o':	/* Output text file with the sorted numbers..  */
          args_info->sortXXL_options_mode_counter += 1;
        
        
          if (update_arg( (void *)&(args_info->output_arg), 
               &(args_info->output_orig), &(args_info->output_given),
              &(local_args_info.output_given), optarg, 0, 0, ARG_STRING,
              check_ambiguity, override, 0, 0,
              "output", 'o',
              additional_error))
            goto failure;
        
          break;
        case 'b':	/* Benchmark mode. Number of times that sortXXL that will execute, presenting the execution time in the end..  */
          args_info->sortXXL_options_mode_counter += 1;
        
        
          if (update_arg( (void *)&(args_info->benchmark_arg), 
               &(args_info->benchmark_orig), &(args_info->benchmark_given),
              &(local_args_info.benchmark_given), optarg, 0, "1", ARG_INT,
              check_ambiguity, override, 0, 0,
              "benchmark", 'b',
              additional_error))
            goto failure;
        
          break;
        case 'm':	/* Minimum value to be sorted..  */
          args_info->sortXXL_options_mode_counter += 1;
        
        
          if (update_arg( (void *)&(args_info->min_arg), 
               &(args_info->min_orig), &(args_info->min_given),
              &(local_args_info.min_given), optarg, 0, 0, ARG_INT,
              check_ambiguity, override, 0, 0,
              "min", 'm',
              additional_error))
            goto failure;
        
          break;
        case 'M':	/* Maximum value to be sorted..  */
          args_info->sortXXL_options_mode_counter += 1;
        
        
          if (update_arg( (void *)&(args_info->max_arg), 
               &(args_info->max_orig), &(args_info->max_given),
              &(local_args_info.max_given), optarg, 0, 0, ARG_INT,
              check_ambiguity, override, 0, 0,
              "max", 'M',
              additional_error))
            goto failure;
        
          break;
        case 'd':	/* Demo mode with the port specification to listen for connections from HTTP clients.  */
          args_info->sortXXL_options_mode_counter += 1;
        
        
          if (update_arg( (void *)&(args_info->demo_arg), 
               &(args_info->demo_orig), &(args_info->demo_given),
              &(local_args_info.demo_given), optarg, 0, "7681", ARG_INT,
              check_ambiguity, override, 0, 0,
              "demo", 'd',
              additional_error))
            goto failure;
        
          break;
        case 'g':	/* Show graphic card's information..  */
        
        
          if (update_arg((void *)&(args_info->gpu_flag), 0, &(args_info->gpu_given),
              &(local_args_info.gpu_given), optarg, 0, 0, ARG_FLAG,
              check_ambiguity, override, 1, 0, "gpu", 'g',
              additional_error))
            goto failure;
        
          break;

        case 0:	/* Long option with no short option */
          /* Application credits..  */
          if (strcmp (long_options[option_index].name, "about") == 0)
          {
          
            if (args_info->data_source_group_counter && override)
              reset_group_data_source (args_info);
            args_info->data_source_group_counter += 1;
          
            if (update_arg( 0 , 
                 0 , &(args_info->about_given),
                &(local_args_info.about_given), optarg, 0, 0, ARG_NO,
                check_ambiguity, override, 0, 0,
                "about", '-',
                additional_error))
              goto failure;
          
          }
          
          break;
        case '?':	/* Invalid option.  */
          /* `getopt_long' already printed an error message.  */
          goto failure;

        default:	/* bug: option not considered.  */
          fprintf (stderr, "%s: option unknown: %c%s\n", CMDLINE_PARSER_PACKAGE, c, (additional_error ? additional_error : ""));
          abort ();
        } /* switch */
    } /* while */

  if (args_info->data_source_group_counter > 1)
    {
      fprintf (stderr, "%s: %d options of group data source were given. One is required%s.\n", argv[0], args_info->data_source_group_counter, (additional_error ? additional_error : ""));
      error = 1;
    }
  


  if (check_required)
    {
      error += cmdline_parser_required2 (args_info, argv[0], additional_error);
    }

  cmdline_parser_release (&local_args_info);

  if ( error )
    return (EXIT_FAILURE);

  return 0;

failure:
  
  cmdline_parser_release (&local_args_info);
  return (EXIT_FAILURE);
}
